<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "restaurant_ldvcdhtl"
 *
 * Auto generated by Extension Builder 2020-05-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Restaurant LDVCDHTL',
    'description' => 'Carte de restaurant',
    'category' => 'plugin',
    'author' => 'Dilan Hassan, Valentin Carrichon, Théau Leclere, Laurie Dumery, David Jacquelin',
    'author_email' => 'dilan.hassan@etu.u-bordeaux.fr, valentin.carrichon@etu.u-bordeaux.fr, theau.leclere@etu.u-bordeaux.fr, laurie.dumery@etu.u-bordeaux.fr, david.jacquelin@etu.u-bordeaux.fr',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
